name: Release Rascal-LSP
on:
  workflow_dispatch:
  push:
    tags:
      - 'rascal-lsp-[0-9]+.*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deployments
    defaults:
      run:
        working-directory: ./rascal-lsp

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'

      - name: Package & compile rascal-lsp
        run: mvn -B clean verify

      - name: Deploy
        uses: usethesource/releases-maven-action@v1
        with:
          maven-username: ${{ secrets.RELEASE_MAVEN_USERNAME }}
          maven-password: ${{ secrets.RELEASE_MAVEN_PASSWORD }}
          maven-local-port: ${{ secrets.RELEASE_MAVEN_LOCAL_PORT }}
          ssh-hostname: ${{ secrets.RELEASE_SSH_SERVER }}
          ssh-known-host: ${{ secrets.RELEASE_SSH_KNOWN_HOSTS }}
          ssh-username: ${{ secrets.RELEASE_SSH_USERNAME }}
          ssh-private-key: ${{ secrets.RELEASE_SSH_PRIVATE_KEY }}
          working-directory: ./rascal-lsp
